package rpg

import (
	"graphdb/internal/graph"
	"strings"
	"testing"
)

// MockGlobalClusterer for testing Global Discovery Mode
type MockGlobalClusterer struct{}

func (m *MockGlobalClusterer) Cluster(nodes []graph.Node, domain string) (map[string][]graph.Node, error) {
	// Returns two clusters: "AuthGroup" and "PaymentGroup"
	clusters := make(map[string][]graph.Node)

	// Filter nodes for AuthGroup
	var authNodes []graph.Node
	for _, n := range nodes {
		if p, ok := n.Properties["file"].(string); ok && (p == "src/auth/login.go" || p == "src/auth/logout.go") {
			authNodes = append(authNodes, n)
		}
	}
	clusters["AuthGroup"] = authNodes

	// Filter nodes for PaymentGroup
	var payNodes []graph.Node
	for _, n := range nodes {
		if p, ok := n.Properties["file"].(string); ok && (strings.HasPrefix(p, "src/payment/")) {
			payNodes = append(payNodes, n)
		}
	}
	clusters["PaymentGroup"] = payNodes

	return clusters, nil
}

func TestBuilder_GlobalBuild(t *testing.T) {
	// Setup
	// We don't need a real Discoverer for Global Mode, but Builder struct might require one if not careful.
	// In the new implementation, if GlobalClusterer is present, Discoverer should be ignored.
	builder := &Builder{
		GlobalClusterer: &MockGlobalClusterer{},
		Clusterer:       &MockClusterer{}, // Reusing MockClusterer from builder_test.go (assumed in same package)
	}

	// Input: Functions
	functions := []graph.Node{
		{ID: "func1", Properties: map[string]interface{}{"file": "src/auth/login.go", "name": "Login"}},
		{ID: "func2", Properties: map[string]interface{}{"file": "src/auth/logout.go", "name": "Logout"}},
		{ID: "func3", Properties: map[string]interface{}{"file": "src/payment/charge.go", "name": "Charge"}},
		{ID: "func4", Properties: map[string]interface{}{"file": "src/payment/refund.go", "name": "Refund"}},
	}

	// Execute
	features, edges, err := builder.Build("src/", functions)
	if err != nil {
		t.Fatalf("Build failed: %v", err)
	}

	if len(edges) == 0 {
		t.Errorf("Expected edges, got 0")
	}

	// Verify Structure
	// We expect 2 domains:
	// 1. AuthGroup -> LCA "src/auth" -> Named likely "domain-auth"
	// 2. PaymentGroup -> LCA "src/payment" -> Named likely "domain-payment"

	if len(features) != 2 {
		t.Errorf("Expected 2 domain features, got %d", len(features))
	}

	// Check Domain Names (generated by NamingStrategy)
	// Since GenerateDomainName uses LCA and then "top term", let's inspect what we got.
	// LCA for AuthGroup is "src/auth". Base is "auth". Name should be "domain-auth".
	// LCA for PaymentGroup is "src/payment". Base is "payment". Name should be "domain-payment".

	foundAuth := false
	foundPayment := false

	for _, f := range features {
		t.Logf("Found feature: ID=%s Name=%s ScopePath=%s", f.ID, f.Name, f.ScopePath)
		if f.Name == "domain-auth" || f.ID == "domain-auth" {
			foundAuth = true
			if f.ScopePath != "src/auth" {
				t.Errorf("Expected Auth domain ScopePath 'src/auth', got '%s'", f.ScopePath)
			}
		}
		if f.Name == "domain-payment" || f.ID == "domain-payment" {
			foundPayment = true
			if f.ScopePath != "src/payment" {
				t.Errorf("Expected Payment domain ScopePath 'src/payment', got '%s'", f.ScopePath)
			}
		}
	}

	if !foundAuth {
		t.Errorf("Did not find Auth domain")
	}
	if !foundPayment {
		t.Errorf("Did not find Payment domain")
	}

	// Verify that MockClusterer was called for 2-level hierarchy (Domain -> Feature)
	// In Global Mode, we still use b.Clusterer to break down the domain into features.
	// MockClusterer creates 1 cluster per domain.
	// So each domain should have 1 child feature.

	for _, f := range features {
		if len(f.Children) != 1 {
			t.Errorf("Expected 1 child feature for domain %s, got %d", f.Name, len(f.Children))
		}
	}
}
